# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Question.create(genre_id:'2', question_name:'あわせていくつ？', question_content: '○○  ○○○ あわせていくつかな？',tip: 'まるをかぞえてみよう', model_answer: '5つ', point: '50', user_id: '1' )
Question.create(genre_id:'2', question_name:'あわせていくつ？', question_content: '☆  ☆☆☆☆ あわせていくつかな？',tip: 'ほしをかぞえてみよう', model_answer: '5つ', point: '50', user_id: '1' )
Question.create(genre_id:'2', question_name:'ぜんぶでなんほん?', question_content: 'しろいおはなが6ほん、あおいおはなが2ほん。ぜんぶでなんほん？',tip: '⑥と②を合わせると・・・', model_answer: '8ほん', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'ぜんぶでなんひき？', question_content: 'くろいさかなが5ひき、あかいさかなが3ひき。ぜんぶでなんひき？',tip: 'しきになおすと5と３をたすから・・・', model_answer: '8ひき', point: '120', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '2+5',tip: 'チョキとパーだね', model_answer: '7', point: '70', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '4+2',tip: 'ヒントなし', model_answer: '6', point: '200', user_id: '1' )
Question.create(genre_id:'2', question_name:'しきになおしてみよう', question_content: '○○○ + ○○○○',tip: 'それぞれなんこずつあるかな？', model_answer: '3+4', point: '130', user_id: '1' )
Question.create(genre_id:'2', question_name:'しきになおしてみよう', question_content: 'ネコが5ひきいます。そこにほかのネコが3ひきやってきました。みんなでなんひきになるか、しきをかこう',tip: 'こたえじゃなくてしきをかくんだよ', model_answer: '5+3', point: '180', user_id: '1' )
Question.create(genre_id:'2', question_name:'しきになおしてみよう', question_content: 'アヒルが2ひきいます。そこにほかのアヒルが4ひきやってきました。みんなでなんひきになるか、しきをかこう',tip: 'しきをかくんだよ', model_answer: '2+4', point: '180', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '2+1',tip: 'ヒントなし', model_answer: '3', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '1+3',tip: 'ヒントなし', model_answer: '4', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '2+3',tip: 'ヒントなし', model_answer: '5', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '5+4',tip: 'ヒントなし', model_answer: '9', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '3+5',tip: 'ヒントなし', model_answer: '8', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '7+2',tip: 'ヒントなし', model_answer: '9', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '3+3',tip: 'ヒントなし', model_answer: '6', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '8+2',tip: 'ヒントなし', model_answer: '10', point: '200', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '4+6',tip: 'ヒントなし', model_answer: '10', point: '200', user_id: '1' )
Question.create(genre_id:'2', question_name:'これ、なぁんだ', question_content: '0 (なんとよむかな？)',tip: '1よりもっとちいさいよ', model_answer: 'れい (ゼロでもせいかい!)', point: '200', user_id: '1' )
Question.create(genre_id:'2', question_name:'ふえないたしざん', question_content: '2+0',tip: '0をたすとふえるのかな？', model_answer: '2', point: '150', user_id: '1' )
Question.create(genre_id:'2', question_name:'ふえないたしざん', question_content: '0+3',tip: '0に３をたすんだね', model_answer: '3', point: '150', user_id: '1' )
Question.create(genre_id:'2', question_name:'ふえないたしざん', question_content: '0+0',tip: '', model_answer: '0', point: '220', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '3+1',tip: 'ヒントなし', model_answer: '4', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '4+5',tip: 'ヒントなし', model_answer: '9', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '7+1',tip: 'ヒントなし', model_answer: '8', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '2+7',tip: 'ヒントなし', model_answer: '9', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '1+6',tip: 'ヒントなし', model_answer: '7', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '4+2',tip: 'ヒントなし', model_answer: '6', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '3+4',tip: 'ヒントなし', model_answer: '7', point: '100', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '3+7',tip: 'ヒントなし', model_answer: '10', point: '160', user_id: '1' )
Question.create(genre_id:'2', question_name:'たしざん', question_content: '9+1',tip: 'ヒントなし', model_answer: '10', point: '160', user_id: '1' )