users = []
10.times do |i|
  users << User.new(nickname: "dummy-#{i+1}", email: "test#{i+1}@test.com", password: '111111', character_name: 'たまご', level: 1, experience_point: 0 )
end
User.import users

levels = []
100.times do |l|
  level =+ l+1
  levels << LevelSetting.new(level: l+1, thresold: level**3)
end
LevelSetting.import levels

EvolutionSetting.create(id:1, level:5,  character_name:'ようちゅう')
EvolutionSetting.create(id:2, level:15, character_name:'サナギ')
EvolutionSetting.create(id:3, level:30, character_name:'カブトムシ')
EvolutionSetting.create(id:4, level:40, character_name:'エレファスゾウカブト')
EvolutionSetting.create(id:5, level:50, character_name:'アトラスオオカブト')
EvolutionSetting.create(id:6, level:60, character_name:'ネプチューンオオカブト')
EvolutionSetting.create(id:7, level:70, character_name:'コーカサスオオカブト')
EvolutionSetting.create(id:8, level:85, character_name:'ヘラクレスオオカブト')

Question.create(id: 1, 
                genre_id:'2',
                question_name:'あわせていくつ？',
                question_content: "○○  ○○○ あわせていくつかな？",
                tip: 'まるをかぞえてみよう',
                model_answer: '5つ',
                point: '20',
                user_id: '5')
Question.create(id: 2,
                genre_id:'2',
                question_name:'あわせていくつ？',
                question_content: "☆  ☆☆☆☆ あわせていくつかな？",
                tip: 'ほしをかぞえてみよう',
                model_answer: '5つ',
                point: '20',
                user_id: '5')
Question.create(id: 3,
                genre_id:'2',
                question_name:'ぜんぶでなんほん？',
                question_content: "しろいおはなが6ほん、あおいおはなが2ほん。ぜんぶでなんほん？",
                tip: '⑥と②を合わせると・・・',
                model_answer: '8ほん',
                point: '20',
                user_id: '5')
Question.create(id: 4,
                genre_id:'2',
                question_name:'ぜんぶでなんひき？',
                question_content: "くろいさかなが5ひき、あかいさかなが3ひき。ぜんぶでなんひき？",
                tip: 'しきになおすと5と３をたすから・・・',
                model_answer: '8ひき',
                point: '20',
                user_id: '5')
Question.create(id: 5,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "2+5",
                tip: 'チョキとパーだね',
                model_answer: '7',
                point: '30',
                user_id: '5')
Question.create(id: 6,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "4+2",
                tip: 'ヒントなし',
                model_answer: '6',
                point: '30',
                user_id: '5')
Question.create(id: 7,
                genre_id:'2',
                question_name:'しきになおしてみよう',
                question_content: "○○○ + ○○○○",
                tip: 'それぞれなんこずつあるかな？',
                model_answer: '3+4',
                point: '100',
                user_id: '5')
Question.create(id: 8,
                genre_id:'2',
                question_name:'しきになおしてみよう',
                question_content: "ネコが5ひきいます。そこにほかのネコが3ひきやってきました。みんなでなんひきになるか、しきをかこう",
                tip: 'こたえじゃなくてしきをかくんだよ',
                model_answer: '5+3',
                point: '150',
                user_id: '5')
Question.create(id: 9,
                genre_id:'2',
                question_name:'しきになおしてみよう',
                question_content: "アヒルが2ひきいます。そこにほかのアヒルが4ひきやってきました。みんなでなんひきになるか、しきをかこう",
                tip: 'しきをかくんだよ',
                model_answer: '2+4',
                point: '180',
                user_id: '5')
Question.create(id: 10,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "2+1",
                tip: 'ヒントなし',
                model_answer: '3',
                point: '110',
                user_id: '5')
Question.create(id: 11,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "1+3",
                tip: 'ヒントなし',
                model_answer: '4',
                point: '110',
                user_id: '5')
Question.create(id: 12,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "2+3",
                tip: 'ヒントなし',
                model_answer: '5',
                point: '110',
                user_id: '5')
Question.create(id: 13,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "5+4",
                tip: 'ヒントなし',
                model_answer: '9',
                point: '120',
                user_id: '5')
Question.create(id: 14,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "3+5",
                tip: 'ヒントなし',
                model_answer: '8',
                point: '130',
                user_id: '5')
Question.create(id: 15,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "7+2",
                tip: 'ヒントなし',
                model_answer: '9',
                point: '130',
                user_id: '5')
Question.create(id: 16,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "3+3",
                tip: 'ヒントなし',
                model_answer: '6',
                point: '130',
                user_id: '5')
Question.create(id: 17,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "8+2",
                tip: 'ヒントなし',
                model_answer: '10',
                point: '150',
                user_id: '5')
Question.create(id: 18,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "4+6",
                tip: 'ヒントなし',
                model_answer: '10',
                point: '160',
                user_id: '5')
Question.create(id: 19,
                genre_id:'2',
                question_name:'これ、なぁんだ',
                question_content: "0 (なんとよむかな？)",
                tip: '1よりもっとちいさいよ',
                model_answer: 'れい',
                point: '200',
                user_id: '5')
Question.create(id: 20,
                genre_id:'2',
                question_name:'ふえないたしざん',
                question_content: "2+0",
                tip: '0をたすとふえるのかな？',
                model_answer: '2',
                point: '150',
                user_id: '5')
Question.create(id: 21,
                genre_id:'2',
                question_name:'ふえないたしざん',
                question_content: "0+3",
                tip: '0に３をたすんだね',
                model_answer: '3',
                point: '150',
                user_id: '5')
Question.create(id: 22,
                genre_id:'2',
                question_name:'ふえないたしざん',
                question_content: "0+0",
                tip: '',
                model_answer: '0',
                point: '220',
                user_id: '5')
Question.create(id: 23,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "3+1",
                tip: 'ヒントなし',
                model_answer: '4',
                point: '120',
                user_id: '5')
Question.create(id: 24,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "4+5",
                tip: 'ヒントなし',
                model_answer: '9',
                point: '120',
                user_id: '5')
Question.create(id: 25,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "7+1",
                tip: 'ヒントなし',
                model_answer: '8',
                point: '120',
                user_id: '5')
Question.create(id: 26,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "2+7",
                tip: 'ヒントなし',
                model_answer: '9',
                point: '120',
                user_id: '5')
Question.create(id: 27,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "1+6",
                tip: 'ヒントなし',
                model_answer: '7',
                point: '120',
                user_id: '5')
Question.create(id: 28,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "4+2",
                tip: 'ヒントなし',
                model_answer: '6',
                point: '120',
                user_id: '5')
Question.create(id: 29,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "3+4",
                tip: 'ヒントなし',
                model_answer: '7',
                point: '120',
                user_id: '5')
Question.create(id: 30,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "3+7",
                tip: 'ヒントなし',
                model_answer: '10',
                point: '160',
                user_id: '5')
Question.create(id: 31,
                genre_id:'2',
                question_name:'たしざん',
                question_content: "9+1",
                tip: 'ヒントなし',
                model_answer: '10',
                point: '160',
                user_id: '5')
Question.create(id: 32,
                genre_id:'2',
                question_name:'のこりはいくつ',
                question_content: "みかんが３つあります。１つたべました。のこりはいくつ？",
                tip: 'たべたらへっちゃうね',
                model_answer: '2つ',
                point: '160',
                user_id: '5')
Question.create(id: 33,
                genre_id:'2',
                question_name:'のこりはいくひき',
                question_content: "テントウムシが５ひきいます。１ひきとんでいきました。のこりはなんひき？",
                tip: '絵にかいてみるとわかりやすいよ',
                model_answer: '４ひき',
                point: '160',
                user_id: '5')
Question.create(id: 34,
                genre_id:'2',
                question_name:'しきになおしてみよう',
                question_content: "テントウムシが５ひきいます。１ひきとんでいきました。のこりはなんひき？？",
                tip: 'しきになおすんだよ',
                model_answer: '5-1',
                point: '200',
                user_id: '5')
Question.create(id: 35,
                genre_id:'2',
                question_name:'しきになおしてみよう',
                question_content: "おはなを3ほんもっています。おともだちに1ぽんあげました。のこりはなんほん？",
                tip: 'おともだちになんほんあげたかな？しきになおすんだよ',
                model_answer: '3-1',
                point: '200',
                user_id: '5')
Question.create(id: 36,
                genre_id:'2',
                question_name:'しきになおしてみよう',
                question_content: "ふうせんを5こもっています。3ことんでいってしまいました。のこりはなんこ？",
                tip: 'ふうせんがどうなったかな？しきになおすんだよ',
                model_answer: '5-3',
                point: '220',
                user_id: '5')
Question.create(id: 37,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "5-3",
                tip: 'ふうせんを5こもっています。3ことんでいってしまいました。のこりはなんこ？',
                model_answer: '2こ',
                point: '220',
                user_id: '5')
Question.create(id: 38,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "5-4",
                tip: '○○○○○ - ○○○○ = ?',
                model_answer: '1',
                point: '230',
                user_id: '5')
Question.create(id: 39,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "4-2",
                tip: '○○○○ - ○○ = ??',
                model_answer: '2',
                point: '230',
                user_id: '5')
Question.create(id: 40,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "9-5",
                tip: '○○○○○○○○○ - ○○○○○ = ????',
                model_answer: '4',
                point: '230',
                user_id: '5')
Question.create(id: 41,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "6-1",
                tip: '',
                model_answer: '5',
                point: '260',
                user_id: '5')
Question.create(id: 42,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "8-2",
                tip: '',
                model_answer: '6',
                point: '260',
                user_id: '5')
Question.create(id: 43,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "7-4",
                tip: '',
                model_answer: '3',
                point: '270',
                user_id: '5')
Question.create(id: 44,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "9-7",
                tip: '',
                model_answer: '2',
                point: '300',
                user_id: '5')
Question.create(id: 45,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "10-3",
                tip: '',
                model_answer: '7',
                point: '320',
                user_id: '5')
Question.create(id: 46,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "10-6",
                tip: '',
                model_answer: '4',
                point: '340',
                user_id: '5')
Question.create(id: 47,
                genre_id:'2',
                question_name:'ひきざんを、こたえよう',
                question_content: "しろとくろのうさぎが、あわせて8ひきいます。しろいうさぎは3ひきです。くろいうさぎはなんひき？",
                tip: 'ひきざんをすると、くろいうさぎのかずがわかるよ',
                model_answer: '5ひき',
                point: '350',
                user_id: '5')
Question.create(id: 48,
                genre_id:'2',
                question_name:'むずかしいひきざん',
                question_content: "まるが9こあります。●が4こです。○はなんこ？",
                tip: '●○○●○●○○●',
                model_answer: '5こ',
                point: '370',
                user_id: '5')
Question.create(id: 49,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "3-1=",
                tip: '3から1ひくと...？',
                model_answer: '2',
                point: '300',
                user_id: '5')
Question.create(id: 50,
                genre_id:'2',
                question_name:'ひきざん',
                question_content: "3-2=",
                tip: '3から2ひくと...？',
                model_answer: '1',
                point: '300',
                user_id: '5')
Question.create(id: 51,
                genre_id:'2',
                question_name:'0のひきざん',
                question_content: "3-3=",
                tip: '3から3ひくと...？',
                model_answer: '0',
                point: '340',
                user_id: '5')
Question.create(id: 52,
                genre_id:'2',
                question_name:'0のひきざん',
                question_content: "3-0=",
                tip: '3から0ひくと...？ん？ひく？？',
                model_answer: '3',
                point: '370',
                user_id: '5')
Question.create(id: 53,
                genre_id:'2',
                question_name:'0のひきざん',
                question_content: "5-5=",
                tip: '',
                model_answer: '0',
                point: '390',
                user_id: '5')
Question.create(id: 54,
                genre_id:'2',
                question_name:'0のひきざん',
                question_content: "6-0=",
                tip: '',
                model_answer: '6',
                point: '395',
                user_id: '5')
Question.create(id: 55,
                genre_id:'2',
                question_name:'0のひきざん',
                question_content: "0-0=",
                tip: '',
                model_answer: '0',
                point: '400',
                user_id: '5')
Question.create(id: 56,
                genre_id:'2',
                question_name:'ちがいのけいさん',
                question_content: "○が8こあります。□は5こあります。○は□よりなんこおおいですか？",
                tip: 'ひきざんでこたえがわかるよ',
                model_answer: '3こ',
                point: '450',
                user_id: '5')
Question.create(id: 57,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "2-1",
                tip: '',
                model_answer: '1',
                point: '300',
                user_id: '5')
Question.create(id: 58,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "6-5",
                tip: '',
                model_answer: '1',
                point: '330',
                user_id: '5')
Question.create(id: 59,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "7-2",
                tip: '',
                model_answer: '5',
                point: '350',
                user_id: '5')
Question.create(id: 60,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "9-2",
                tip: '',
                model_answer: '7',
                point: '370',
                user_id: '5')
Question.create(id: 61,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "8-4",
                tip: '',
                model_answer: '4',
                point: '370',
                user_id: '5')
Question.create(id: 62,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "6-3",
                tip: '',
                model_answer: '3',
                point: '370',
                user_id: '5')
Question.create(id: 63,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "9-6",
                tip: '',
                model_answer: '3',
                point: '370',
                user_id: '5')
Question.create(id: 64,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "10-4",
                tip: '',
                model_answer: '6',
                point: '390',
                user_id: '5')
Question.create(id: 65,
                genre_id:'2',
                question_name:'ひきざんをしよう',
                question_content: "10-8",
                tip: '',
                model_answer: '2',
                point: '400',
                user_id: '5')
Question.create(id: 66,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "2-?=1",
                tip: '?には、なにがはいるかな？',
                model_answer: '1',
                point: '420',
                user_id: '5')
Question.create(id: 67,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "6-?=1",
                tip: '?には、なにがはいるかな？',
                model_answer: '5',
                point: '420',
                user_id: '5')
Question.create(id: 68,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "7-?=5",
                tip: '?には、なにがはいるかな？',
                model_answer: '2',
                point: '420',
                user_id: '5')
Question.create(id: 69,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "9-?=7",
                tip: '?には、なにがはいるかな？',
                model_answer: '2',
                point: '420',
                user_id: '5')
Question.create(id: 70,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "8-?=4",
                tip: '?には、なにがはいるかな？',
                model_answer: '4',
                point: '420',
                user_id: '5')
Question.create(id: 71,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "?-3=3",
                tip: '?には、なにがはいるかな？',
                model_answer: '6',
                point: '440',
                user_id: '5')
Question.create(id: 72,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "?-6=3",
                tip: '?には、なにがはいるかな？',
                model_answer: '9',
                point: '440',
                user_id: '5')
Question.create(id: 73,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "?-4=6",
                tip: '',
                model_answer: '10',
                point: '460',
                user_id: '5')
Question.create(id: 74,
                genre_id:'2',
                question_name:'ひきざんをかんせいさせよう',
                question_content: "?-8=2",
                tip: '',
                model_answer: '10',
                point: '460',
                user_id: '5')
Question.create(id: 75,
                genre_id:'2',
                question_name:'ひきざんをかんせいできるかな？',
                question_content: "?-8=0",
                tip: '',
                model_answer: '8',
                point: '480',
                user_id: '5')
Question.create(id: 76,
                genre_id:'2',
                question_name:'おぼえているかな？',
                question_content: "4+2=",
                tip: '',
                model_answer: '6',
                point: '400',
                user_id: '5')
Question.create(id: 77,
                genre_id:'2',
                question_name:'おぼえているかな？',
                question_content: "1+6=",
                tip: '',
                model_answer: '7',
                point: '400',
                user_id: '5')
Question.create(id: 78,
                genre_id:'2',
                question_name:'おぼえているかな？',
                question_content: "2+8=",
                tip: '',
                model_answer: '10',
                point: '420',
                user_id: '5')
Question.create(id: 79,
                genre_id:'2',
                question_name:'おぼえているかな？',
                question_content: "3+5=",
                tip: '',
                model_answer: '8',
                point: '420',
                user_id: '5')
Question.create(id: 80,
                genre_id:'2',
                question_name:'おぼえているかな？',
                question_content: "6+3=",
                tip: '',
                model_answer: '9',
                point: '420',
                user_id: '5')
Question.create(id: 81,
                genre_id:'2',
                question_name:'おぼえているかな？',
                question_content: "4+4=",
                tip: '',
                model_answer: '8',
                point: '420',
                user_id: '5')
Question.create(id: 82,
                genre_id:'2',
                question_name:'おおきいたしざん',
                question_content: "10+3=",
                tip: '10のくらいと1のくらいとで、わけられるよ',
                model_answer: '13',
                point: '450',
                user_id: '5')
Question.create(id: 83, 
                genre_id:'2',
                question_name:'おおきいたしざん',
                question_content: "10+6=",
                tip: '10のくらいと1のくらいとで、わけられるよ',
                model_answer: '16',
                point: '450',
                user_id: '5')
Question.create(id: 84, 
                genre_id:'2',
                question_name:'おおきいたしざん',
                question_content: "10+9=",
                tip: '10のくらいと1のくらいとで、わけられるよ',
                model_answer: '19',
                point: '450',
                user_id: '5')
Question.create(id: 85, 
                genre_id:'2',
                question_name:'おおきいたしざんをかんせいさせよう',
                question_content: "10+?=15",
                tip: 'ひきざんをすると?がわかるよ',
                model_answer: '5',
                point: '480',
                user_id: '5')
Question.create(id: 86, 
                genre_id:'2',
                question_name:'おおきいたしざんをかんせいさせよう',
                question_content: "10+?=18",
                tip: 'ひきざんをすると?がわかるよ',
                model_answer: '8',
                point: '480',
                user_id: '5')
Question.create(id: 87, 
                genre_id:'2',
                question_name:'どちらがおおきいでしょうか',
                question_content: "17と19",
                tip: '10のくらいはおなじだね。1のくらいは？',
                model_answer: '19',
                point: '450',
                user_id: '5')
Question.create(id: 88, 
                genre_id:'2',
                question_name:'どちらがおおきいでしょうか',
                question_content: "20と12",
                tip: '10のくらいがちがうね',
                model_answer: '20',
                point: '480',
                user_id: '5')
Question.create(id: 89, 
                genre_id:'2',
                question_name:'たしざんだよ',
                question_content: "12+4=",
                tip: '10のくらいと1のくらいで、わけてかんがえてみよう',
                model_answer: '16',
                point: '500',
                user_id: '5')
Question.create(id: 90, 
                genre_id:'2',
                question_name:'たしざんだよ',
                question_content: "14+3=",
                tip: '10のくらいと1のくらいで、わけてかんがえてみよう',
                model_answer: '17',
                point: '500',
                user_id: '5')
Question.create(id: 91, 
                genre_id:'2',
                question_name:'ひきざんだよ',
                question_content: "17-5=",
                tip: '',
                model_answer: '12',
                point: '540',
                user_id: '5')
Question.create(id: 92,
                genre_id:'2',
                question_name:'ひきざんだよ',
                question_content: "19-3=",
                tip: '',
                model_answer: '16',
                point: '540',
                user_id: '5')
Question.create(id: 93,
                genre_id:'2',
                question_name:'ひきざんだよ',
                question_content: "18-6=",
                tip: '',
                model_answer: '12',
                point: '540',
                user_id: '5')
Question.create(id: 94,
                genre_id:'2',
                question_name:'3つのかずのたしざん',
                question_content: "2+4+1=",
                tip: '4+1で5になるね',
                model_answer: '7',
                point: '580',
                user_id: '5')
Question.create(id: 95,
                genre_id:'2',
                question_name:'3つのかずのたしざん',
                question_content: "9+1+3=",
                tip: '9+1で10になって、そこに3をたすと？',
                model_answer: '13',
                point: '580',
                user_id: '5')
Question.create(id: 96,
                genre_id:'2',
                question_name:'3つのかずのたしざん',
                question_content: "4+6+2=",
                tip: '4+6で10になって、そこに2をたすと？',
                model_answer: '12',
                point: '580',
                user_id: '5')
Question.create(id: 97,
                genre_id:'2',
                question_name:'3つのかずのひきざん',
                question_content: "9-3-4=",
                tip: 'まず、9-3で6になって...そこから4をひくと？',
                model_answer: '2',
                point: '620',
                user_id: '5')
Question.create(id: 98,
                genre_id:'2',
                question_name:'3つのかずのひきざん',
                question_content: "12-2-1=",
                tip: 'まず、10-2で10になって...そこから1をひくと？',
                model_answer: '9',
                point: '620',
                user_id: '5')
Question.create(id: 99,
                genre_id:'2',
                question_name:'3つのかずのひきざん',
                question_content: "13-3-7=",
                tip: 'まず、13-3で10になって...',
                model_answer: '3',
                point: '640',
                user_id: '5')
Question.create(id: 100,
                genre_id:'2',
                question_name:'スペシャルもんだい',
                question_content: "9-3-3-3=",
                tip: 'ふふふふ',
                model_answer: '0',
                point: '1050',
                user_id: '5')
Question.create(id: 101,
                genre_id:'2',
                question_name:'たしたり、ひいたり',
                question_content: "6-2+4=",
                tip: 'じゅんばんにけいさんしよう。まずは6-2から',
                model_answer: '8',
                point: '700',
                user_id: '5')
Question.create(id: 102,
                genre_id:'2',
                question_name:'たしたり、ひいたり',
                question_content: "10-9+3=",
                tip: 'まずは10-9をけいさんして',
                model_answer: '4',
                point: '700',
                user_id: '5')
Question.create(id: 103,
                genre_id:'2',
                question_name:'たしたり、ひいたり',
                question_content: "10-3+2=",
                tip: 'まずは10-3をけいさんして',
                model_answer: '9',
                point: '700',
                user_id: '5')
Question.create(id: 104,
                genre_id:'2',
                question_name:'たしたり、ひいたり',
                question_content: "5+3-1=",
                tip: 'まずは5+3をけいさんして、そこから1ひくと？',
                model_answer: '7',
                point: '700',
                user_id: '5')
Question.create(id: 105,
                genre_id:'2',
                question_name:'たしたり、ひいたり',
                question_content: "6+4-5=",
                tip: '6+4は10だね。そこからひくのは？いくつ？',
                model_answer: '5',
                point: '700',
                user_id: '5')
Question.create(id: 106,
                genre_id:'2',
                question_name:'たしたり、ひいたり',
                question_content: "2+8-3=",
                tip: '',
                model_answer: '7',
                point: '750',
                user_id: '5')
Question.create(id: 107,
                genre_id:'2',
                question_name:'たしたり、ひいたり',
                question_content: "2+8+3=",
                tip: '',
                model_answer: '13',
                point: '720',
                user_id: '5')
Question.create(id: 108,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "9+5=",
                tip: '9は、あと1つで10になるね。5は、1と4にわけられるね。',
                model_answer: '14',
                point: '750',
                user_id: '5')
Question.create(id: 109,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "8+4=",
                tip: '8は、あと2つで10になるね。4は、2と2にわけられるね。',
                model_answer: '12',
                point: '750',
                user_id: '5')
Question.create(id: 110,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "7+6=",
                tip: '7は、あと3つで10になるね。6は、3と3にわけられるね。',
                model_answer: '13',
                point: '750',
                user_id: '5')
Question.create(id: 111,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "8+7=",
                tip: '8は、あといくつで10になるかな。',
                model_answer: '15',
                point: '750',
                user_id: '5')
Question.create(id: 112,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "7+5=",
                tip: '7は、あと3つで10になるね。',
                model_answer: '12',
                point: '750',
                user_id: '5')
Question.create(id: 113,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "9+8=",
                tip: '9は、あと1つで10になるね。',
                model_answer: '17',
                point: '750',
                user_id: '5')
Question.create(id: 114,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "6+5=",
                tip: '',
                model_answer: '11',
                point: '780',
                user_id: '5')
Question.create(id: 115,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "8+8=",
                tip: '',
                model_answer: '16',
                point: '780',
                user_id: '5')
Question.create(id: 116,
                genre_id:'2',
                question_name:'くりあがりのけいさん',
                question_content: "9+7=",
                tip: '',
                model_answer: '16',
                point: '780',
                user_id: '5')
Question.create(id: 117,
                genre_id:'2',
                question_name:'くりさがりのけいさん',
                question_content: "10-7=",
                tip: '',
                model_answer: '3',
                point: '780',
                user_id: '5')
Question.create(id: 118,
                genre_id:'2',
                question_name:'くりさがりのけいさん',
                question_content: "12-7=",
                tip: '12が10になるには-2だから...。7-2でのこり5だから。10-5で？？',
                model_answer: '5',
                point: '780',
                user_id: '5')
Question.create(id: 119,
                genre_id:'2',
                question_name:'くりさがりのけいさん',
                question_content: "13-5=",
                tip: '13は10と3に分ける。10-5は5。あまってた3と、5をたすと？',
                model_answer: '8',
                point: '780',
                user_id: '5')
Question.create(id: 120,
                genre_id:'2',
                question_name:'あといくつで10になる？',
                question_content: "6はあといくつで10になりますか？",
                tip: '10-6は？',
                model_answer: '4',
                point: '780',
                user_id: '5')
Question.create(id: 121,
                genre_id:'2',
                question_name:'あといくつで10になる？',
                question_content: "4はあといくつで10になりますか？",
                tip: '10-4は？',
                model_answer: '6',
                point: '780',
                user_id: '5')
Question.create(id: 122,
                genre_id:'2',
                question_name:'くりさがりのけいさん',
                question_content: "11-8=",
                tip: '11は10と1にわけられる',
                model_answer: '8',
                point: '800',
                user_id: '5')
Question.create(id: 123,
                genre_id:'2',
                question_name:'くりさがりのけいさん',
                question_content: "16-9=",
                tip: '',
                model_answer: '7',
                point: '840',
                user_id: '5')
Question.create(id: 124,
                genre_id:'2',
                question_name:'くりさがりのけいさん',
                question_content: "13-7=",
                tip: '',
                model_answer: '6',
                point: '840',
                user_id: '5')
Question.create(id: 125,
                genre_id:'2',
                question_name:'くりさがりのけいさん',
                question_content: "12-8=",
                tip: '',
                model_answer: '4',
                point: '840',
                user_id: '5')
Question.create(id: 126,
                genre_id:'2',
                question_name:'くりさがりのけいさん',
                question_content: "12-6=",
                tip: '',
                model_answer: '6',
                point: '840',
                user_id: '5')
Question.create(id: 127,
                genre_id:'2',
                question_name:'おおきいかず',
                question_content: "十のくらいが3、一のくらいが８のかずは？",
                tip: '10が３こで30だよ',
                model_answer: '38',
                point: '870',
                user_id: '5')
Question.create(id: 128,
                genre_id:'2',
                question_name:'おおきいかず',
                question_content: "十のくらいが5、一のくらいが0のかずは？",
                tip: '10が5こで50だよ',
                model_answer: '50',
                point: '870',
                user_id: '5')
Question.create(id: 129,
                genre_id:'2',
                question_name:'おおきいかず',
                question_content: "70の十のくらいのすうじは？",
                tip: '10がいくつかな？',
                model_answer: '7',
                point: '850',
                user_id: '5')
Question.create(id: 130,
                genre_id:'2',
                question_name:'すごくおおきいかず',
                question_content: "10が10こで百になります。すうじであらわしてください",
                tip: '99よりも1おおきいです',
                model_answer: '100',
                point: '900',
                user_id: '5')
Question.create(id: 131,
                genre_id:'2',
                question_name:'どちらがおおきいですか',
                question_content: "50と47では、どちらがおおきいですか",
                tip: '十のくらいにちゅういしよう',
                model_answer: '50',
                point: '800',
                user_id: '5')
Question.create(id: 132,
                genre_id:'2',
                question_name:'どちらがおおきいですか',
                question_content: "76と82では、どちらがおおきいですか",
                tip: '十のくらいにちゅういしよう',
                model_answer: '82',
                point: '850',
                user_id: '5')
Question.create(id: 133,
                genre_id:'2',
                question_name:'どちらがおおきいですか',
                question_content: "98と89では、どちらがおおきいですか",
                tip: '',
                model_answer: '98',
                point: '980',
                user_id: '5')
Question.create(id: 134,
                genre_id:'2',
                question_name:'かず と しき',
                question_content: "40+2",
                tip: '十のくらいと一のくらいをかんがえよう',
                model_answer: '42',
                point: '420',
                user_id: '5')
Question.create(id: 135,
                genre_id:'2',
                question_name:'かず と しき',
                question_content: "60+8",
                tip: '',
                model_answer: '68',
                point: '680',
                user_id: '5')
Question.create(id: 136,
                genre_id:'2',
                question_name:'かず と しき',
                question_content: "55-5",
                tip: '十のくらいと一のくらいをかんがえよう',
                model_answer: '50',
                point: '500',
                user_id: '5')
Question.create(id: 137,
                genre_id:'2',
                question_name:'かず と しき',
                question_content: "73-3",
                tip: '',
                model_answer: '70',
                point: '700',
                user_id: '5')
Question.create(id: 138,
                genre_id:'2',
                question_name:'けいさんもんだい',
                question_content: "23+4",
                tip: '',
                model_answer: '27',
                point: '800',
                user_id: '5')
Question.create(id: 139,
                genre_id:'2',
                question_name:'けいさんもんだい',
                question_content: "61+8",
                tip: '',
                model_answer: '69',
                point: '800',
                user_id: '5')
Question.create(id: 140,
                genre_id:'2',
                question_name:'けいさんもんだい',
                question_content: "28-5",
                tip: '',
                model_answer: '23',
                point: '800',
                user_id: '5')
Question.create(id: 141,
                genre_id:'2',
                question_name:'けいさんもんだい',
                question_content: "58-6",
                tip: '',
                model_answer: '52',
                point: '800',
                user_id: '5')
Question.create(id: 142,
                genre_id:'2',
                question_name:'とけいのよみかた',
                question_content: "とけいの『みじかいハリ』が8をむいています。なんじですか？",
                tip: 'みじかいはりは○○じをあらわすよ',
                model_answer: '8じ',
                point: '900',
                user_id: '5')
Question.create(id: 143,
                genre_id:'2',
                question_name:'とけいのよみかた',
                question_content: "とけいの『みじかいハリ』が12をむいています。なんじですか？",
                tip: '',
                model_answer: '12じ',
                point: '900',
                user_id: '5')
Question.create(id: 144,
                genre_id:'2',
                question_name:'とけいのよみかた',
                question_content: "とけいの『ながいハリ』が1をむいています。なんふんですか？",
                tip: '1までに小さいめもりが5つあるよ',
                model_answer: '5ふん',
                point: '900',
                user_id: '5')
Question.create(id: 145,
                genre_id:'2',
                question_name:'とけいのよみかた',
                question_content: "とけいの『ながいハリ』が2をむいています。なんふんですか？",
                tip: '1で5ふん。2で？',
                model_answer: '10ふん',
                point: '900',
                user_id: '5')
Question.create(id: 146,
                genre_id:'2',
                question_name:'とけいのよみかた!!',
                question_content: "『みじかいハリ』が8のほうをむいています。でも『ながいハリ』は11をむいています。なんじなんふん？",
                tip: 'まだ8じになるまえだよ。ながいハリにちゅういしよう！',
                model_answer: '7じ55ふん',
                point: '1200',
                user_id: '5')
Question.create(id: 147,
                genre_id:'2',
                question_name:'とけいのよみかた!!',
                question_content: "『みじかいハリ』が8と9のあいだです。『ながいハリ』は6をむいています。なんじなんふん？",
                tip: '',
                model_answer: '8じ30ふん',
                point: '1500',
                user_id: '5')
Question.create(id: 148,
                genre_id:'2',
                question_name:'ぶんしょうもんだい',
                question_content: "Aさんはまえから6ばんめにならんでいます。Aさんのうしろには4にんいます。みんなでなんにんならんでいますか？",
                tip: 'たしざんでこたえがだせるよ',
                model_answer: '10にん',
                point: '1000',
                user_id: '5')
Question.create(id: 149,
                genre_id:'2',
                question_name:'ぶんしょうもんだい',
                question_content: "おとなが6にんいます。こどもが13にんいます。あわせてなんにんいますか？",
                tip: 'たしざんでこたえがだせるよ',
                model_answer: '19にん',
                point: '1000',
                user_id: '5')
Question.create(id: 150,
                genre_id:'2',
                question_name:'ぶんしょうもんだい',
                question_content: "おとなが6にんいます。こどもが13にんいます。こどもはなんにんおおいですか？",
                tip: 'ひきざんでこたえがだせるよ',
                model_answer: '7にん',
                point: '1000',
                user_id: '5')
Question.create(id: 151,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "あ",
                tip: '『かな』もじでa(A)だよ！',
                model_answer: 'あ',
                point: '100',
                user_id: '5')
Question.create(id: 152,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "い",
                tip: '『かな』もじでi(I)だよ！',
                model_answer: 'い',
                point: '100',
                user_id: '5')
Question.create(id: 153,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "う",
                tip: '『かな』もじでu(U)だよ！',
                model_answer: 'う',
                point: '100',
                user_id: '5')
Question.create(id: 154,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "え",
                tip: '『かな』もじでe(E)だよ！',
                model_answer: 'え',
                point: '100',
                user_id: '5')
Question.create(id: 155,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "お",
                tip: '『かな』もじでo(O)だよ！',
                model_answer: 'お',
                point: '100',
                user_id: '5')
Question.create(id: 156,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "あいうえお",
                tip: '『かな』もじにする必要があるよ！',
                model_answer: 'あいうえお',
                point: '250',
                user_id: '5')
Question.create(id: 157,
                genre_id:'1',
                question_name:'カタカナでおなじもじをうってみよう',
                question_content: "アイウエオ",
                tip: '『カナ』もじにする必要があるよ！',
                model_answer: 'アイウエオ',
                point: '350',
                user_id: '5')
Question.create(id: 158,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "か",
                tip: 'k(K)とa(A)で『か』になるよ！さがしてみよう',
                model_answer: 'か',
                point: '500',
                user_id: '5')
Question.create(id: 159,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "き",
                tip: 'k(K)とi(I)で『き』になるよ！さがしてみよう',
                model_answer: 'き',
                point: '500',
                user_id: '5')
Question.create(id: 160,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "く",
                tip: 'k(K)とu(U)で『く』になるよ！さがしてみよう',
                model_answer: 'く',
                point: '500',
                user_id: '5')
Question.create(id: 161,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "け",
                tip: 'k(K)とe(E)で『け』になるよ！さがしてみよう',
                model_answer: 'け',
                point: '500',
                user_id: '5')
Question.create(id: 162,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "こ",
                tip: 'k(K)とo(O)で『こ』になるよ！さがしてみよう',
                model_answer: 'こ',
                point: '500',
                user_id: '5')
Question.create(id: 163,
                genre_id:'1',
                question_name:'"のつくもじをうってみよう',
                question_content: "『が』とうってみよう",
                tip: 'g(G)とa(A)で『が』になるよ！さがしてみよう',
                model_answer: 'が',
                point: '500',
                user_id: '5')
Question.create(id: 164,
                genre_id:'1',
                question_name:'"のつくもじをうってみよう',
                question_content: "『ぎ』とうってみよう",
                tip: 'g(G)とi(I)で『ぎ』になるよ！さがしてみよう',
                model_answer: 'ぎ',
                point: '500',
                user_id: '5')
Question.create(id: 165,
                genre_id:'1',
                question_name:'"のつくもじをうってみよう',
                question_content: "『げ』とうってみよう",
                tip: 'g(G)とe(E)で『げ』になるよ！さがしてみよう',
                model_answer: 'げ',
                point: '500',
                user_id: '5')
Question.create(id: 166,
                genre_id:'1',
                question_name:'"のつくもじをうってみよう',
                question_content: "『ご』とうってみよう",
                tip: 'g(G)とo(O)で『ご』になるよ！さがしてみよう',
                model_answer: 'ご',
                point: '500',
                user_id: '5')
Question.create(id: 167,
                genre_id:'1',
                question_name:'"のつくもじをうってみよう',
                question_content: "『がぎぐげご』とうってみよう",
                tip: 'g(G)とaiueo(あいうえお)で『が行』になるよ！',
                model_answer: 'ご',
                point: '800',
                user_id: '5')
Question.create(id: 168,
                genre_id:'1',
                question_name:'さ行のもじをうってみよう',
                question_content: "『さしすせそ』とうってみよう",
                tip: 's(S)とaiueo(あいうえお)で『さ行』になるよ！',
                model_answer: 'さしすせそ',
                point: '800',
                user_id: '5')
Question.create(id: 169,
                genre_id:'1',
                question_name:'ざ行のもじをうってみよう',
                question_content: "『ざじずぜぞ』とうってみよう",
                tip: 'z(Z)とaiueo(あいうえお)で『ざ行』になるよ！',
                model_answer: 'ざじずぜぞ',
                point: '800',
                user_id: '5')
Question.create(id: 170,
                genre_id:'1',
                question_name:'た行のもじをうってみよう',
                question_content: "『たちつてと』とうってみよう",
                tip: 't(T)とaiueo(あいうえお)で『た行』になるよ！',
                model_answer: 'たちつてと',
                point: '800',
                user_id: '5')
Question.create(id: 171,
                genre_id:'1',
                question_name:'だ行のもじをうってみよう',
                question_content: "『だぢづでど』とうってみよう",
                tip: 'd(D)とaiueo(あいうえお)で『ざ行』になるよ！',
                model_answer: 'だぢづでど',
                point: '800',
                user_id: '5')
Question.create(id: 172,
                genre_id:'1',
                question_name:'な行のもじをうってみよう',
                question_content: "『なにぬねの』とうってみよう",
                tip: 'n(N)とaiueo(あいうえお)で『な行』になるよ！',
                model_answer: 'なにぬねの',
                point: '800',
                user_id: '5')
Question.create(id: 173,
                genre_id:'1',
                question_name:'は行のもじをうってみよう',
                question_content: "『はひふへほ』とうってみよう",
                tip: 'h(H)とaiueo(あいうえお)で『は行』になるよ！',
                model_answer: 'はひふへほ',
                point: '800',
                user_id: '5')
Question.create(id: 174,
                genre_id:'1',
                question_name:'ば行のもじをうってみよう',
                question_content: "『ばびぶべぼ』とうってみよう",
                tip: 'b(B)とaiueo(あいうえお)で『ば行』になるよ！',
                model_answer: 'ばびぶべぼ',
                point: '800',
                user_id: '5')
Question.create(id: 175,
                genre_id:'1',
                question_name:'ま行のもじをうってみよう',
                question_content: "『まみむめも』とうってみよう",
                tip: 'm(M)とaiueo(あいうえお)で『ま行』になるよ！',
                model_answer: 'まみむめも',
                point: '800',
                user_id: '5')
Question.create(id: 176,
                genre_id:'1',
                question_name:'や行のもじをうってみよう',
                question_content: "『やゆよ』とうってみよう",
                tip: 'y(Y)とa u o(あ う お)で『や行』になるよ！',
                model_answer: 'やゆよ',
                point: '900',
                user_id: '5')
Question.create(id: 177,
                genre_id:'1',
                question_name:'ら行のもじをうってみよう',
                question_content: "『らりるれろ』とうってみよう",
                tip: 'r(R)とaiueo(あいうえお)で『ら行』になるよ！',
                model_answer: 'らりるれろ',
                point: '800',
                user_id: '5')
Question.create(id: 178,
                genre_id:'1',
                question_name:'!?『わ行』のもじをうってみよう!?',
                question_content: "『わをん』とうってみよう",
                tip: 'w(W)とa o(あ お)で『わ行』になるよ！『ん』はn(N)が２回だよ！',
                model_answer: 'わをん',
                point: '1350',
                user_id: '5')
Question.create(id: 179,
                genre_id:'1',
                question_name:'『ローマじ』をうってみよう',
                question_content: "『やま』とうってみよう",
                tip: '『や』はY(わい)とA(えー)で、『ま』はm(えむ)とa(えー)だよ！',
                model_answer: 'やま',
                point: '900',
                user_id: '5')
Question.create(id: 180,
                genre_id:'1',
                question_name:'『ローマじ』をうってみよう',
                question_content: "『めだか』とうってみよう",
                tip: '『め』はm(M)、『だ』はd(D)、『か』はk(K)のなかまだよ。',
                model_answer: 'めだか',
                point: '1200',
                user_id: '5')
Question.create(id: 181,
                genre_id:'1',
                question_name:'『ちいさい』もじをうってみよう',
                question_content: "ちいさい『ぁ』とうってみよう",
                tip: '『あ』はa(A)だね。小さくするには、l(L)とa(A)だよ！',
                model_answer: 'ぁ',
                point: '1200',
                user_id: '5')
Question.create(id: 182,
                genre_id:'1',
                question_name:'『ちいさい』もじをうってみよう',
                question_content: "ちいさい『ぃ』とうってみよう",
                tip: '『い』はi(I)だね。小さくするには、l(L)とi(I)だよ！',
                model_answer: 'ぃ',
                point: '1200',
                user_id: '5')
Question.create(id: 183,
                genre_id:'1',
                question_name:'『ちいさい』もじをうってみよう',
                question_content: "ちいさい『ぅ』とうってみよう",
                tip: '『う』はu(U)だね。小さくするには、l(L)とu(U)だよ！',
                model_answer: 'ぅ',
                point: '1200',
                user_id: '5')
Question.create(id: 184,
                genre_id:'1',
                question_name:'『ちいさい』もじをうってみよう',
                question_content: "ちいさい『ぇ』とうってみよう",
                tip: '『え』はe(E)だね。小さくするには、l(L)とe(E)だよ！',
                model_answer: 'ぇ',
                point: '1200',
                user_id: '5')
Question.create(id: 185,
                genre_id:'1',
                question_name:'『ちいさい』もじをうってみよう',
                question_content: "ちいさい『ぉ』とうってみよう",
                tip: '『お』はo(O)だね。小さくするには、l(L)とo(O)だよ！',
                model_answer: 'ぉ',
                point: '1200',
                user_id: '5')
Question.create(id: 186,
                genre_id:'1',
                question_name:'『ちいさい』もじをうってみよう',
                question_content: "ちいさい『ゃ』とうってみよう",
                tip: '『や』はy(Y)とa(A)だね。小さくするには、l(L)と『YA』だよ！',
                model_answer: 'ゃ',
                point: '1200',
                user_id: '5')
Question.create(id: 187,
                genre_id:'1',
                question_name:'『ちいさい』もじをうってみよう',
                question_content: "ちいさい『ゅ』とうってみよう",
                tip: '『ゆ』はy(Y)とu(U)だね。小さくするには、l(L)と『YU』だよ！',
                model_answer: 'ゅ',
                point: '1200',
                user_id: '5')
Question.create(id: 188,
                genre_id:'1',
                question_name:'『ちいさい』もじをうってみよう',
                question_content: "ちいさい『ょ』とうってみよう",
                tip: '『よ』はy(Y)とo(O)だね。小さくするには、l(L)と『YO』だよ！',
                model_answer: 'ょ',
                point: '1200',
                user_id: '5')
Question.create(id: 189,
                genre_id:'1',
                question_name:'『ローマじ』をうってみよう',
                question_content: "『ちょこ』とうってみよう",
                tip: '『ち+ょ+こ』だね。TI+LYO+KO',
                model_answer: 'ちょこ',
                point: '1250',
                user_id: '5')
Question.create(id: 190,
                genre_id:'1',
                question_name:'『ローマじ』をうってみよう',
                question_content: "『じゃむ』とうってみよう",
                tip: '『じ+ゃ+む』だね。JI+LYA+MU',
                model_answer: 'じゃむ',
                point: '1250',
                user_id: '5')
Question.create(id: 191,
                genre_id:'1',
                question_name:'『ローマじ』をうってみよう',
                question_content: "かんたんなほうほうで『じゃむ』とうってみよう",
                tip: '『じゃ+む』だね。JYA+MUとできるよ',
                model_answer: 'じゃむ',
                point: '1350',
                user_id: '5')
Question.create(id: 192,
                genre_id:'1',
                question_name:'ぱ行のもじをうってみよう',
                question_content: "『ぱぴぷぺぽ』とうってみよう",
                tip: 'p(P)とaiueo(あいうえお)で『ぱ行』になるよ！',
                model_answer: 'ぱぴぷぺぽ',
                point: '800',
                user_id: '5')
Question.create(id: 193,
                genre_id:'1',
                question_name:'『ローマじ』をうってみよう',
                question_content: "『ぷりん』とうってみよう",
                tip: '『ぷ+り+ん』だね。',
                model_answer: 'ぷりん',
                point: '1350',
                user_id: '5')
Question.create(id: 194,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『一つ』はなんとよむ？",
                tip: 'うんどうかいで、たまいれきょうそうのときにかぞえたね',
                model_answer: 'ひとつ',
                point: '1350',
                user_id: '5')
Question.create(id: 195,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『一まい』はなんとよむ？",
                tip: 'かみをかぞえるときだよ',
                model_answer: 'いちまい',
                point: '1350',
                user_id: '5')
Question.create(id: 196,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『二つ』はなんとよむ？",
                tip: '',
                model_answer: 'ふたつ',
                point: '800',
                user_id: '5')
Question.create(id: 197,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『三つ』はなんとよむ？",
                tip: '',
                model_answer: 'みっつ',
                point: '1500',
                user_id: '5')
Question.create(id: 198,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『四つ』はなんとよむ？",
                tip: '',
                model_answer: 'よっつ',
                point: '1300',
                user_id: '5')
Question.create(id: 199,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『五つ』はなんとよむ？",
                tip: 'ごっつではないよ！',
                model_answer: 'いつつ',
                point: '1700',
                user_id: '5')
Question.create(id: 200,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『六つ』はなんとよむ？",
                tip: 'ろくつではないよ！',
                model_answer: 'むっつ',
                point: '1400',
                user_id: '5')
Question.create(id: 201,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『七つ』はなんとよむ？",
                tip: '',
                model_answer: 'ななつ',
                point: '1000',
                user_id: '5')
Question.create(id: 202,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『八つ』はなんとよむ？",
                tip: 'はちつではないよ！',
                model_answer: 'やっつ',
                point: '1500',
                user_id: '5')
Question.create(id: 203,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『九つ』はなんとよむ？",
                tip: 'きゅうつではないよ！',
                model_answer: 'ここのつ',
                point: '1500',
                user_id: '5')
Question.create(id: 204,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『子ども』はなんとよむ？",
                tip: 'KODOMO',
                model_answer: 'こども',
                point: '1800',
                user_id: '5')
Question.create(id: 205,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『天』はなんとよむ？",
                tip: 'TENN',
                model_answer: 'てん',
                point: '1800',
                user_id: '5')
Question.create(id: 206,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『男の子』はなんとよむ？",
                tip: '',
                model_answer: 'おとこのこ',
                point: '1800',
                user_id: '5')
Question.create(id: 207,
                genre_id:'1',
                question_name:'よみかたをこたえよう',
                question_content: "『青』はなんとよむ？",
                tip: '',
                model_answer: 'あお',
                point: '1800',
                user_id: '5')
Question.create(id: 208,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "『やればできる』",
                tip: '',
                model_answer: 'やればできる',
                point: '1200',
                user_id: '5')
Question.create(id: 209,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "『はやねはやおき』",
                tip: '',
                model_answer: 'はやねはやおき',
                point: '1200',
                user_id: '5')
Question.create(id: 210,
                genre_id:'1',
                question_name:'おなじもじをうってみよう',
                question_content: "『いいてんき』",
                tip: '',
                model_answer: 'いいてんき',
                point: '1200',
                user_id: '5')
Question.create(id: 211,
                genre_id:'1',
                question_name:'カタカナになおそう',
                question_content: "『かっぷ』",
                tip: '',
                model_answer: 'カップ',
                point: '800',
                user_id: '5')
Question.create(id: 212,
                genre_id:'1',
                question_name:'カタカナになおそう',
                question_content: "『れもん』",
                tip: '',
                model_answer: 'レモン',
                point: '800',
                user_id: '5')
Question.create(id: 213,
                genre_id:'1',
                question_name:'カタカナになおそう',
                question_content: "『じゅーす』",
                tip: 'ーは＝とおなじボタンだよ！',
                model_answer: 'ジュース',
                point: '1700',
                user_id: '5')
Question.create(id: 214,
                genre_id:'1',
                question_name:'カタカナになおそう',
                question_content: "『らーめん』",
                tip: '',
                model_answer: 'ラーメン',
                point: '1850',
                user_id: '5')
Question.create(id: 215,
                genre_id:'1',
                question_name:'かんじになおそう',
                question_content: "かんじ",
                tip: 'KANNJI',
                model_answer: '漢字',
                point: '1200',
                user_id: '5')
Question.create(id: 216,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "みる",
                tip: 'まえをみる',
                model_answer: '見る',
                point: '1200',
                user_id: '5')
Question.create(id: 217,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "ぶん",
                tip: 'BUNN',
                model_answer: '文',
                point: '1200',
                user_id: '5')
Question.create(id: 218,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "ただしい",
                tip: 'TADASII',
                model_answer: '正しい',
                point: '1200',
                user_id: '5')
Question.create(id: 219,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "むし",
                tip: 'MUSI',
                model_answer: '虫',
                point: '1200',
                user_id: '5')
Question.create(id: 220,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "そら",
                tip: 'SORA',
                model_answer: '空',
                point: '1200',
                user_id: '5')
Question.create(id: 221,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "あおい",
                tip: 'AOI',
                model_answer: '青い',
                point: '1200',
                user_id: '5')
Question.create(id: 222,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "かわ",
                tip: 'KAWA',
                model_answer: '川',
                point: '1200',
                user_id: '5')
Question.create(id: 223,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "みず",
                tip: 'MIZU',
                model_answer: '水',
                point: '1200',
                user_id: '5')
Question.create(id: 224,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "にちようび",
                tip: 'NITIYOUBI',
                model_answer: '日曜日',
                point: '1500',
                user_id: '5')
Question.create(id: 225,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "げつようび",
                tip: 'GETUYOUBI',
                model_answer: '月曜日',
                point: '1500',
                user_id: '5')
Question.create(id: 226,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "かようび",
                tip: 'KAYOUBI',
                model_answer: '火曜日',
                point: '1500',
                user_id: '5')
Question.create(id: 227,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "すいようび",
                tip: 'SUIYOUBI',
                model_answer: '水曜日',
                point: '1500',
                user_id: '5')
Question.create(id: 228,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "もくようび",
                tip: 'MOKUYOUBI',
                model_answer: '木曜日',
                point: '1500',
                user_id: '5')
Question.create(id: 229,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "きんようび",
                tip: 'KINNYOUBI',
                model_answer: '金曜日',
                point: '1500',
                user_id: '5')
Question.create(id: 230,
                genre_id:'1',
                question_name:'漢字になおそう',
                question_content: "どようび",
                tip: 'DOYOUBI',
                model_answer: '土曜日',
                point: '1500',
                user_id: '5')
Question.create(id: 231,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "三日",
                tip: '三月三日だよ。『さんひ』ではないよ',
                model_answer: 'みっか',
                point: '1250',
                user_id: '5')
Question.create(id: 232,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "四日",
                tip: '四月四日だよ。『よんにち』ではないよ',
                model_answer: 'よっか',
                point: '1250',
                user_id: '5')
Question.create(id: 233,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "五日",
                tip: '五月五日だよ。『ごにち』ではないよ',
                model_answer: 'いつか',
                point: '1250',
                user_id: '5')
Question.create(id: 234,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "六日",
                tip: '六月六日だよ。『ろくにち』ではないよ',
                model_answer: 'むいか',
                point: '1250',
                user_id: '5')
Question.create(id: 235,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "七日",
                tip: '七月七日だよ。『ななにち』ではないよ',
                model_answer: 'なのか',
                point: '1250',
                user_id: '5')
Question.create(id: 236,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "八日",
                tip: '八月八日だよ。『はちにち』ではないよ',
                model_answer: 'なのか',
                point: '1250',
                user_id: '5')
Question.create(id: 237,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "九日",
                tip: '九月九日だよ。『きゅうにち』ではないよ',
                model_answer: 'ここのか',
                point: '1250',
                user_id: '5')
Question.create(id: 238,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "十日",
                tip: '十月十日だよ。『じゅうにち』ではないよ',
                model_answer: 'とおか',
                point: '1500',
                user_id: '5')
Question.create(id: 239,
                genre_id:'1',
                question_name:'日にちのよみかた',
                question_content: "二十日",
                tip: '十二月二十日だよ。『にじゅうにち』ではないよ',
                model_answer: 'はつか',
                point: '2000',
                user_id: '5')
Question.create(id: 240,
                genre_id:'1',
                question_name:'○に入る漢字はなんでしょう？',
                question_content: "一、十、○、千",
                tip: '1、10、○、1000',
                model_answer: '百',
                point: '1200',
                user_id: '5')
Question.create(id: 241,
                genre_id:'1',
                question_name:'漢字を入力しよう',
                question_content: "がっこう",
                tip: 'GAKKOU',
                model_answer: '学校',
                point: '1000',
                user_id: '5')
Question.create(id: 242,
                genre_id:'1',
                question_name:'『 』の中の漢字を読もう',
                question_content: "川の『音』",
                tip: '',
                model_answer: 'おと',
                point: '1350',
                user_id: '5')
Question.create(id: 243,
                genre_id:'1',
                question_name:'『 』の中の漢字を読もう',
                question_content: "村の『人』",
                tip: '',
                model_answer: 'ひと',
                point: '1350',
                user_id: '5')
Question.create(id: 244,
                genre_id:'1',
                question_name:'『 』の中の漢字を読もう',
                question_content: "白い『花』",
                tip: '',
                model_answer: 'はな',
                point: '1350',
                user_id: '5')
Question.create(id: 245,
                genre_id:'1',
                question_name:'『 』の中の漢字を読もう',
                question_content: "赤い『花』",
                tip: '',
                model_answer: 'はな',
                point: '1350',
                user_id: '5')
Question.create(id: 246,
                genre_id:'1',
                question_name:'『 』の中のひらがなを漢字にしよう',
                question_content: "いすから『たつ』",
                tip: '',
                model_answer: '立つ',
                point: '1500',
                user_id: '5')
Question.create(id: 247,
                genre_id:'1',
                question_name:'『 』の中のひらがなを漢字にしよう',
                question_content: "『くさ』をたべる",
                tip: '',
                model_answer: '草',
                point: '1500',
                user_id: '5')
Question.create(id: 248,
                genre_id:'1',
                question_name:'『 』の中のひらがなを漢字にしよう',
                question_content: "かわいい『いぬ』",
                tip: '',
                model_answer: '犬',
                point: '1500',
                user_id: '5')
Question.create(id: 249,
                genre_id:'1',
                question_name:'『 』の中のひらがなを漢字にしよう',
                question_content: "『はやく』おきる",
                tip: '',
                model_answer: '早く',
                point: '1500',
                user_id: '5')
Question.create(id: 250,
                genre_id:'1',
                question_name:'『 』の中のひらがなを漢字にしよう',
                question_content: "『おもいで』",
                tip: '',
                model_answer: '思い出',
                point: '1700',
                user_id: '5')